loadFramePacks([
	{name:'Set Showcase Frames (Chronological)', value:'disabled'},
	{name:'Stained Glass (DMU)', value:'DMUStainedGlass'},
	{name:'Golden Age (SNC)', value:'SNCGilded'},
	{name:'Art Deco (SNC)', value:'SNCArtDeco'},
	{name:'Skyscraper (SNC)', value:'SNCSkyscraper'},
	{name:'Ninja (NEO)', value:'NeoNinja'},
	{name:'Samurai (NEO)', value:'NeoSamurai'},
	{name:'Neon (NEO)', value:'NeoNeon'},
	{name:'Fang (VOW)', value:'Fang'},
	{name:'Equinox (MID)', value:'Equinox'},
	{name:'Eternal Night (MID)', value:'EternalNight'},
	{name:'D&D Sourcebook (AFR)', value:'DNDSourcebook'},
	{name:'D&D Module (AFR)', value:'DNDModule'},
	{name:'Sketch Cards (MH2)', value:'MH2'},
	{name:'Mystical Archive (STA)', value:'MysticalArchive'},
	{name:'Japanese Mystical Archive (STA)', value:'MysticalArchiveJP'},
	{name:'Horizontal Japanese Mystical Archive (STA)', value:'MysticalArchiveJPHorizontal'},
	{name:'Praetors (KHM)', value:'Praetors'},
	{name:'Kaldheim (KHM)', value:'Kaldheim-2'},
	{name:'Nonlegendary Kaldheim (KHM)', value:'KaldheimNonleg'},
	{name:'Commander Legends (CMR)', value:'CommanderLegends'},
	{name:'Zendikar Rising (ZNR)', value:'ZendikarRising'},
	{name:'M21 Signature Spellbooks (M21)', value:'M21'},
	{name:'Theros Beyond Death (THB)', value:'M15NyxShowcase'},
	{name:'Eldraine Storybooks (ELD)', value:'Storybook'},
	{name:'Generic Showcase Frames', value:'disabled'},
	{name:'Borderless', value:'GenericShowcase'},
	{name:'Fullart', value:'M15ClearTextboxes'},
	{name:'Nickname ("Godzilla")', value:'M15Nickname'},
	{name:'Extended Art (Regular)', value:'M15BoxTopper'},
	{name:'Extended Art (Shorter Textbox)', value:'M15ExtendedArtShort'},
	{name:'FNM Promo (Inverted Promos)', value:'FNM'},
	{name:'Universes Beyond', value:'UB'},
	{name:'Full Text', value:'FullText'},
	{name:'Etched (Commander Precons)', value:'Etched'},
	{name:'Masterpieces/Other', value:'disabled'},
	{name:'ZNR Expeditions (2020)', value:'ExpeditionZNR-1'},
	{name:'Signature Spellbook (Jace/Gideon)', value:'SignatureSpellbook'},
	{name:'Ixalan Maps', value:'Ixalan'},
	{name:'Amonkhet Invocations (u/Smyris)', value:'Invocation'},
	{name:'Kaladesh Inventions', value:'Invention'},
	{name:'BFZ Expeditions (2015)', value:'ExpeditionBFZ-1'},
	{name:'SDCC15 (Blackout)', value:'SDCC15'},
	{name:'Future Shifted', value:'FutureRegular'},
	{name:'Addons', value:'disabled'},
	{name:'Legend Crowns', value:'M15LegendCrowns'},
	{name:'Floating Legend Crowns', value:'M15LegendCrownsFloating'},
	{name:'Inner Crowns', value:'M15InnerCrowns'},
	{name:'Holo Stamps', value:'M15HoloStamps'},
	{name:'Dark Power/Toughness', value:'M15DarkPT'},
	{name:'Colored Borders', value:'M15Borders'},
	{name:'Color Identity Pips', value:'M15CIPips'},
	{name:'"The List" Stamp', value:'TheList'},
	{name:'Custom Addons', value:'disabled'},
	{name:'Brawl Legend Crowns', value:'Brawl'}
])