loadFramePacks([
	{name:'Regular', value:'ModalRegular'},
	{name:'Borderless', value:'ModalBorderless'},
	{name:'Extended Art', value:'ModalExtended'},
	{name:'Nickname', value:'ModalNickname'},
	{name:'Short', value:'ModalShort'},
	{name:'Short-Nickname', value:'ModalShortNickname'},
	{name:'Addons', value:'disabled'},
	{name:'Regular Legend Crowns', value:'ModalLegendCrowns'},
	{name:'Floating Legend Crowns', value:'ModalLegendCrownsFloating'},
	{name:'Nickname Legend Crowns', value:'ModalLegendCrownsNickname'},
	{name:'Brawl Legend Crowns', value:'ModalLegendCrownsBrawl'},
	{name:'Inner Crowns', value:'M15InnerCrowns'},
	{name:'Holo Stamps', value:'M15HoloStamps'},
	{name:'Dark Power/Toughness', value:'M15DarkPT'},
	{name:'Colored Borders', value:'M15Borders'},
	{name:'Color Identity Pips', value:'M15CIPips'},
	{name:'"The List" Stamp', value:'TheList'},
	{name:'Misc', value:'disabled'},
	{name:'Helper Cards', value:'ModalHelper'}
])