loadFramePacks([
	{name:'Basic Lands', value:'disabled'},
	{name:'Kamigawa Basics (NEO)', value:'NeoBasics'},
	{name:'Fullart Basics (SNC)', value:'TextlessBasicsSNC'},
	{name:'Fullart Basics (THB)', value:'TextlessBasics'},
	{name:'Fullart Basics (ZEN)', value:'ZendikarBasic-1'},
	{name:'Fullart Snow Basics', value:'FullartBasicRoundBottom'},
	{name:'Unstable Basics (UST)', value:'Unstable'},
	{name:'Unhinged Basics (UNH)', value:'Unhinged'},
	{name:'Other', value:'disabled'},
	{name:'Generic Showcase', value:'TextlessGenericShowcase'},
	{name:'Magic Fest Promos', value:'MagicFest'},
	{name:'Addons', value:'disabled'},
	{name:'Legend Crowns', value:'M15LegendCrowns'},
	{name:'Floating Legend Crowns', value:'M15LegendCrownsFloating'},
	{name:'Inner Crowns', value:'M15InnerCrowns'},
	{name:'Holo Stamps', value:'M15HoloStamps'},
	{name:'Dark Power/Toughness', value:'M15DarkPT'},
	{name:'Colored Borders', value:'M15Borders'},
	{name:'"The List" Stamp', value:'TheList'},
	{name:'Custom Addons', value:'disabled'},
	{name:'Brawl Legend Crowns', value:'Brawl'}
])