loadFramePacks([
	{name:'Transform (Front)', value:'M15TransformFront'},
	{name:'Transform (Back)', value:'M15TransformBack'},
	{name:'Color Identity Pips', value:'M15CIPips'},
	{name:'Transform Icons', value:'M15TransformTypes'},
	{name:'Other Cardtypes', value:'disabled'},
	{name:'Sagas (Front)', value:'SagaDFC'},
	{name:'Other Frames', value:'disabled'},
	{name:'Borderless (Front)', value:'TransformBorderlessFront'},
	{name:'Borderless (Back)', value:'TransformBorderlessBack'},
	{name:'Extended Art (Front)', value:'TransformExtendedFront'},
	{name:'Extended Art (Back)', value:'TransformExtendedBack'},
	{name:'SDCC15 (Blackout)', value:'TransformSDCC15'},
	{name:'Addons', value:'disabled'},
	{name:'Legend Crowns', value:'TransformLegendCrowns'},
	{name:'Floating Legend Crowns', value:'TransformLegendCrownsFloating'},
	{name:'Nickname Legend Crowns', value:'TransformLegendCrownsNickname'},
	{name:'Inner Crowns', value:'M15InnerCrowns'},
	{name:'Holo Stamps', value:'M15HoloStamps'},
	{name:'Dark Power/Toughness', value:'M15DarkPT'},
	{name:'"The List" Stamp', value:'TheList'},
	{name:'Custom Addons', value:'disabled'},
	{name:'Brawl Crowns', value:'TransformLegendCrownsBrawl'}
])