loadFramePacks([
	{name:'Misc. Custom Frames', value:'MiscCustom'},
	{name:'Deck Covers', value:'CustomDeckCover'},
	{name:'Simple Inventions', value:'SimpleInventions'},
	{name:'Tapped (Horizontal M15)', value:'Tapped'},
	{name:'Textless Duals', value:'CustomDualLands'},
	{name:'Textless Seventh', value:'SeventhTextless'},
	{name:'Seventh Edition Planeswalkers', value:'PlaneswalkerSeventh'},
	{name:'Seventh Edition Sagas', value:'OldSaga'},
	{name:'Floating Old Border', value:'OldFloating'},
	{name:'Floating Old Border (Short)', value:'OldFloatingShort'},
	{name:'Classicshifted Series', value:'disabled'},
	{name:'Classicshifted', value:'Classicshifted'},
	{name:'Classicshifted Lands', value:'ClassicshiftedLands'},
	{name:'Classicshifted Planeswalkers', value:'ClassicshiftedPlaneswalker'},
	{name:'Classicshifted Planeswalker Transform Addons', value:'ClassicshiftedPlaneswalkerTransform'},
	{name:'Classicshifted Sagas', value:'ClassicshiftedSaga'},
	{name:'Classicshifted MDFC Addons', value:'ClassicshiftedDFC'},
	{name:'Classicshifted Transform Addons', value:'ClassicshiftedTransform'},
	{name:'Color Identity Pips', value:'ClassicshiftedCIPips'},
	{name:'Showcase Frame Varients', value:'disabled'},
	{name:'Short Neon (NEO)', value:'NEONeonShort'},
	{name:'Colored Golden Age (SNC)', value:'SNCGildedColored'},
	{name:'Textless Golden Age (SNC)', value:'SNCGildedTextless'},
	{name:'Textless Equinox (MID)', value:'EquinoxTextless'},
	{name:'Horizontal Japanese Mystical Archive (STA)', value:'MysticalArchiveJPHorizontal'},
	{name:'Extended Art Invocations', value:'AKHInvocationExtended'},
	{name:'Textless Inventions', value:'TextlessInvention'},
	{name:'Custom Addons', value:'disabled'},
	{name:'Brawl Legend Crowns', value:'Brawl'},
	{name:'Custom Community Frames', value:'disabled'},
	{name:'Cartoony - Sheepwave', value:'Cartoony'},
	{name:'Neon - Elry', value:'CustomNeon'},
	{name:'Ixalan - @feuer_ameise', value:'FeuerAmeiseIxalan'},
	{name:'Kaldheim, Fullart - @feuer_ameise', value:'FeuerAmeiseKaldheim'},
	{name:'Celid\'s Asap', value:'CustomCelidAsap'},
	{name:'Magrao\'s Kaldheim', value:'CustomMagraoKaldheim'}
])